character_generator/config/routes.rb
CharacterGeneratorRails::Application.routes.draw do
  resources :dnd_characters

end

character_generator/app/models/dnd_character.rb
class DndCharacter < ActiveRecord::Base
  validates_numericality_of :seed
  validates_length_of :seed, :maximum => 19
end

character_generator/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

character_generator/app/controllers/dnd_characters_controller.rb
require 'prawn'
require "#{File.dirname(__FILE__)}/../../../../D&D 0.5/Character_Generator.rb"

class DndCharactersController < ApplicationController
  # GET /dnd_characters
  # GET /dnd_characters.xml
  def index
    @dnd_characters = DndCharacter.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @dnd_characters }
    end
  end

  # GET /dnd_characters/1
  # GET /dnd_characters/1.xml
  def show
    begin
    @dnd_character = DndCharacter.find(params[:id]) 
    rescue
    puts params[:id]
    @dnd_character = DndCharacter.find_by_name(params[:id]) 
    end
    generator = CharacterGenerator.new
    @character = generator.generate_specific_level_character(15, 4, sources = ["PHB","MM1"], seed = @dnd_character.seed) 

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @dnd_character }
      format.txt  { send_data OutputFormat.string(@character).gsub("\n","\r\n"), :type => 'text/plain', :filename => "#{@character.name}.txt"}
    end
  end

  # GET /dnd_characters/new
  # GET /dnd_characters/new.xml
  def new
    @dnd_character = DndCharacter.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @dnd_character }
    end
  end

  # GET /dnd_characters/1/edit
  def edit
    @dnd_character = DndCharacter.find(params[:id])
  end

  # POST /dnd_characters
  # POST /dnd_characters.xml
  def create
    
    generator = CharacterGenerator.new
    @character = generator.generate_specific_level_character(15, 1, sources = ["PHB","MM1"], seed = params[:dnd_character][:seed].to_i)
    params[:dnd_character][:name] =@character.name.to_s
    @dnd_character = DndCharacter.new(params[:dnd_character])
    puts params

    respond_to do |format|
      if @dnd_character.save
        format.html { redirect_to(@dnd_character, :notice => 'Dnd character was successfully created.') }
        format.xml  { render :xml => @dnd_character, :status => :created, :location => @dnd_character }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @dnd_character.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /dnd_characters/1
  # PUT /dnd_characters/1.xml
  def update
    @dnd_character = DndCharacter.find(params[:id])
    generator = CharacterGenerator.new
    @character = generator.generate_specific_level_character(15, 1, sources = ["PHB","MM1"], seed = params[:dnd_character][:seed].to_i)
    params[:dnd_character][:name] =@character.name.to_s

    respond_to do |format|
      if @dnd_character.update_attributes(params[:dnd_character])
        format.html { redirect_to(@dnd_character, :notice => 'Dnd character was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @dnd_character.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /dnd_characters/1
  # DELETE /dnd_characters/1.xml
  def destroy
    @dnd_character = DndCharacter.find(params[:id])
    @dnd_character.destroy

    respond_to do |format|
      format.html { redirect_to(dnd_characters_url) }
      format.xml  { head :ok }
    end
  end
end

character_generator/app/helpers/application_helper.rb
module ApplicationHelper
end

character_generator/app/helpers/dnd_characters_helper.rb
module DndCharactersHelper
end

character_generator/app/views/dnd_characters/_abilities.html.erb
<table class="smalltable abilities" style="left:<%= left%>px; top:<%= top%>px; width:<%= width%>px;">
<tr id="label"><td>Abilities</td></tr>
<% @character.abilities.collect{|ability| ability.to_s}.sort.each do |ability| %>
<tr id="value"><td><%= ability.to_s %></td></tr>
<% end %>
</table>

character_generator/app/views/dnd_characters/_aclist.html.erb
<table class="aclist" style="left:<%= left%>px; top:<%= top%>px; width:<%= width%>px;">
<tr>
<td id="title">AC:</td>
<td><%= @character.ac_list.values.inject(0){|sum,item| sum.to_i + item.to_i}.to_s %></td><td>=</td>
<% first = true %>
<% @character.ac_list.each do |modifier, bonus| %>
  <td><table><tr>
<% if first then first = false %>
  <td id="value"><%= bonus %></td>
<% else %>
  <td id="value">+ <%= bonus %></td>
<% end %>
  </tr>
  <tr><td id="label"><%= modifier.capitalize %></td></tr></table><td>
<% end %>
</tr></table>

character_generator/app/views/dnd_characters/_appearance.html.erb
<%template_race_list = []
@character.racial_templates.each do |tmplt|
  template_race_list.push(tmplt.to_s)
end %>
<table class="appearance" style="left:<%= left-5%>px; top:<%= top-2%>px; width:<%= width+10%>px;">
<tr>
<td id="value"><%= "#{@character.sex}" %></td>
<td id="value"><%= "#{template_race_list.join(" ")} #{@character.race}" %></td>
<td id="value"><%= "#{@character.age}yrs" %></td>
<td id="value"><%= "#{(@character.height.to_i/12).floor}' #{(@character.height.to_i%12)}\"" %></td>
<td id="value"><%= "#{@character.weight} lbs." %></td>
<td id="value"><%= "#{@character.alignment}"  %></td></tr>
<tr>
<td id="label"><%= "GENDER" %></td>
<td id="label"><%= "RACE" %></td>
<td id="label"><%= "AGE" %></td>
<td id="label"><%= "HEIGHT" %></td>
<td id="label"><%= "WEIGHT" %></td>
<td id="label"><%= "ALIGNMENT" %></td></tr>
</table>

character_generator/app/views/dnd_characters/_classes.html.erb
<table class="classes" style="left:<%= left-5%>px; top:<%= top-2%>px; width:<%= width+10%>px;">
<tr><td id="heading"><%= "Levels: #{@character.level}" %></td></tr>
<% temp_classes = @character.classes.collect {|cls| cls.to_s} %>
<% temp_classes.uniq.each do |cls| %>
<tr><td id="value"><%= "#{cls}(#{temp_classes.count(cls)})" %></td></tr>
<% end %>
<tr><td id="heading"><%= "ECL: #{@character.ECL}" %></td></tr>
</table>

character_generator/app/views/dnd_characters/_feats.html.erb
<table class="smalltable feats" style="left:<%= left%>px; top:<%= top%>px; width:<%= width%>px;">
<tr id="label"><td>Feats</td></tr>
<% @character.feats.collect{|feat| feat.to_s}.sort.each do |feat| %>
<tr id="value"><td><%= feat.to_s %></td></tr>
<% end %>
</table>

character_generator/app/views/dnd_characters/_form.html.erb
<%= form_for(@dnd_character) do |f| %>
  <% if @dnd_character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dnd_character.errors.count, "error") %> prohibited this dnd_character from being saved:</h2>

      <ul>
      <% @dnd_character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :seed %><br />
    <%= f.text_field :seed %>
  </div>
  <div class="field">
    <%= f.label :settings %><br />
    <%= f.text_field :settings %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

character_generator/app/views/dnd_characters/_languages.html.erb
<table class="smalltable languages" style="left:<%= left%>px; top:<%= top%>px; width:<%= width%>px;">
<tr id="label"><td>Languages</td></tr>
<% @character.languages.languages.sort.each do |language| %>
<tr id="value"><td><%= language %></td></tr>
<% end %>
</table>

character_generator/app/views/dnd_characters/_miscstats.html.erb
<table class="miscstats" style="left:<%= left-5%>px; top:<%= top%>px; width:<%= width+10%>px;">
<tr>
<td><table class="splitbubble">
<tr><td id="label">SPEED</td><td id="value"><%= "#{@character.speed} ft." %></td></tr>
</table></td>
</tr>
<tr>
<td><table class="splitbubble">
<tr><td id="label">SR</td><td id="value"><%= "#{@character.spell_resist}" %></td></tr>
</table></td>
</tr>
<tr>
<td><table class="splitbubble">
<tr><td id="label">INIT</td><td id="value"><%= @character.initiative %></td></tr>
</table></td>
</tr>
<tr>
<td><table class="splitbubble">
<tr><td id="label">FORT Save</td><td id="value" >+<%= @character.fort_save.inject(0){|sum,item| sum.to_i + item[1].to_i}.to_s  %></td></tr>
</table></td>
</tr>
<tr>
<td><table class="splitbubble">
<tr><td id="label">REFLEX Save</td><td id="value" >+<%= @character.ref_save.inject(0){|sum,item| sum.to_i + item[1].to_i}.to_s %></td></tr>
</table></td>
</tr>
<tr>
<td><table class="splitbubble">
<tr><td id="label">WILL Save</td><td id="value" >+<%= @character.will_save.inject(0){|sum,item| sum.to_i + item[1].to_i}.to_s %></td></tr>
</table></td>
</tr>
<tr>
<td><table class="splitbubble">
<tr><td id="label">HD</td><td id="value"><%= @character.HD %></td></tr>
</table></td>
</tr>
<tr>
<td><table class="topsplitbubble">
<tr><td id="label">HP</td></tr><tr><td id="value"><%= @character.HP %></td></tr>
</table></td>
</tr>
<tr>
<td><table class="splitbubble">
<tr><td id="label">BAB</td><td id="value">+<%= Array.new((@character.BAB/5).floor + 1){|i| (@character.BAB - i*5).to_s }.join("/+") %></td></tr>
</table></td>
</tr>
</table>

character_generator/app/views/dnd_characters/_skills.html.erb
<table class="skills smalltable" style="left:<%= left%>px; top:<%= top%>px; width:<%= width%>px;">
<tr id="label"><td>Skill Name:</td><td>Total</td><td>Ranks</td><td>Stat</td><td>Bonus</td><td>Circumstance</td></tr>
<% @character.skill_list.skills.sort{ |a,b| a.name <=> b.name }.each do |skill| 
total = @character.stat_mod[skill.mod].to_i + skill.ranks + skill.bonus_hash.inject(0){|sum, bonus| sum += bonus[1]}%>
<tr id="value"><td><%= skill.name %></td>
<td><%= "#{"%+d" % total}"%></td>
<td><%= "= #{skill.ranks}"%></td>
<td><%= "#{"%+d" % @character.stat_mod[skill.mod].to_i} #{skill.mod.upcase}" %></td>
<td><%= skill.bonus_hash.to_a.inject(""){|sum, bonus| sum += " " + ("%+d" % bonus[1].to_i) + " " + bonus[0].to_s } %></td>
<td><%= skill.circumstance_hash.to_a.inject(""){|sum, bonus| sum += " " + ("%+d" % bonus[1].to_i) + " " + bonus[0].to_s } %></td></tr>
<% end %>
</table>

character_generator/app/views/dnd_characters/_stats.html.erb
<table class="stats" style="left:<%= left-5%>px; top:<%= top-2%>px; width:<%= width+10%>px;">
<% statname = {"str"=>"Strength","dex"=>"Dexterity","con"=>"Constitution","int"=>"Intelligence","wis"=>"Wisdom","cha"=>"Charisma"}%>
<% ["str","dex","con","int","wis","cha"].each do |stat| %>
  <% if orient == :horizontal %><tr><% end %>
    <td class="statname" ><table align="center">
    <tr><td class="statname1"><%= "#{stat.upcase}" %></td></tr>
    <tr><td class="statname2"><%= "#{statname[stat]}" %></td></tr>
  </table></td>
  <td class="statval"><%= "#{@character.stats[stat]}" %></td>
	<% if (@character.stat_mod[stat] > 0) %>
    <td class="posmod"><%= "+#{@character.stat_mod[stat]}" %></td>
	<% elsif (@character.stat_mod[stat] == 0) %>
    <td class="zeromod"><%= "#{@character.stat_mod[stat]}" %></td>
  <% else %>
    <td class="negmod"><%= "#{@character.stat_mod[stat]}" %></td>
	<% end %>
  <% if orient == :horizontal %></tr><% end %>
<% end %>
</table>

character_generator/app/views/dnd_characters/edit.html.erb
<h1>Editing dnd_character</h1>

<%= render 'form' %>

<%= link_to 'Show', @dnd_character %> |
<%= link_to 'Back', dnd_characters_path %>

character_generator/app/views/dnd_characters/index.html.erb
<h1>Listing dnd_characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Seed</th>
    <th>Settings</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dnd_characters.each do |dnd_character| %>
  <tr>
    <td><%= dnd_character.name %></td>
    <td><%= dnd_character.seed %></td>
    <td><%= dnd_character.settings %></td>
    <td><%= link_to 'Show', dnd_character %></td>
    <td><%= link_to 'Edit', edit_dnd_character_path(dnd_character) %></td>
    <td><%= link_to 'Destroy', dnd_character, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dnd character', new_dnd_character_path %>

character_generator/app/views/dnd_characters/new.html.erb
<h1>New dnd_character</h1>

<%= render 'form' %>

<%= link_to 'Back', dnd_characters_path %>

character_generator/app/views/dnd_characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dnd_character.name %>
</p>
<% sheet_top = 0; sheet_left = 200 %>
<%= render :partial => "appearance", :locals =>  { :left => sheet_left, :top => sheet_top, :width => 560} %>
<%= render :partial => "aclist", :locals =>  { :left => sheet_left, :top => sheet_top + 50, :width => 560}  %>
<%= render :partial => "stats", :locals => { :orient => :horizontal, :left => sheet_left, :top => sheet_top + 90, :width => 140 } %>
<%= render :partial => "miscstats", :locals =>  { :left => sheet_left + 150, :top => sheet_top + 90, :width => 200} %>
<%= render :partial => "classes", :locals =>  { :left => sheet_left + 360, :top => sheet_top + 90, :width => 200}  %>
<%= render :partial => "abilities", :locals => { :left => sheet_left + 570, :top => sheet_top + 400, :width => 140 } %>
<%= render :partial => "languages", :locals => { :left => sheet_left, :top => sheet_top + 400, :width => 140 } %>
<%= next_top = (@character.languages.languages.length+1) * 17 + sheet_top + 400 + 20 %>
<%= render :partial => "feats", :locals => { :left => sheet_left, :top => next_top, :width => 140 } %>
<%= render :partial => "skills", :locals => { :left => sheet_left + 150, :top => sheet_top + 400, :width => 410} %>
<p>
  <b>Seed:</b>
  <%= @dnd_character.seed %>
</p>

<p>
  <b>Name2:</b>
  <%= @character.name %>
</p>

<p>
  <b>Settings:</b>
  <%= @dnd_character.settings %>
</p>
<%= link_to 'Text File', :controller=>"dnd_characters",:action=>"show", :id =>@dnd_character.name, :format=>"txt" %> |

<%= link_to 'Edit', edit_dnd_character_path(@dnd_character) %> |
<%= link_to 'Back', dnd_characters_path %>

character_generator/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CharacterGeneratorRails</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>